spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&characterEncoding=utf-8&useUnicode=true
    driver: com.mysql.cj.jdbc.Driver
    username: root
    password: root

    hikari:
      maximum-pool-size: 10